name: On Tag pushed
on:
  push:
    tags:
      - v*
jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.21.1'
      - run: go test ./...
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Get version
        id: get_version
        run: |
          VERSION="$(echo '${{ github.ref }}' | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | tr -d '\n')"
          echo "::set-output name=version::${VERSION}"
      - run: git fetch --unshallow
      - name: Generate Changelog
        id: generate_changelog
        uses: PSanetra/git-semver-actions/markdown-log@master
        with:
          version: ${{ steps.get_version.outputs.version }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: Release ${{ steps.get_version.outputs.version }}
          body: |
            ${{ steps.generate_changelog.outputs.changelog }}
          draft: false
          prerelease: false
